### ISSUE TITLE
Support other platforms on import

### ISSUE THREAD

**Issue by kohend** [Heroic-Games-Launcher/heroic-gogdl#31]
Currently, the import command is hard-coded to use the Windows platform, that doesn't allow importing of Linux/MacOS native versions.
 https://github.com/Heroic-Games-Launcher/heroic-gogdl/blob/893a2e6230c51503eb1c8e06df208ebef852f92f/gogdl/imports.py#L96

**Comment by imLinguin** [comment]
If you look at whole function you can see that value is being changed accordingly paths that were found. Meaning it supports `windows`, `osx` and `linux` platforms
