### ISSUE TITLE
Songs of Conquest (AppID 1097426220) downloading wrong version

### ISSUE THREAD

**Issue by becky-soda** [Heroic-Games-Launcher/heroic-gogdl#34]
Using command `$ /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1097426220 --lang=en-US --os windows` returns this data:

```
[API] INFO: Getting info from products endpoint for id: 1097426220
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Songs of Conquest with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 2
[DOWNLOAD_MANAGER] INFO: Getting Meta data
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
[DOWNLOAD_MANAGER] INFO: Calculating download size
{"download_size": 2451209532, "disk_size": 3103338688, "dlcs": [], "buildId": "56504850103710017", "languages": ["en-US"], "folder_name": "Songs of Conquest", "versionEtag": "\"1074652667\"", "versionName": "945b30055c990c8797c045bbcfadb2aa37866bb2"}
```

But looking at the GOG.com website shows the latest version as `44486ac170bb71c9198c23e6f7da4c9b8ecedada`. GOG Galaxy also downloads this version. This inconsistency is causing version mismatch error during multiplayer play through Heroic.

**Important note:** The version shown on the GOG website `44486ac170bb71c9198c23e6f7da4c9b8ecedada` (v0.83.6 - 24 Mar 2023) is _older_ than version `945b30055c990c8797c045bbcfadb2aa37866bb2` (v0.84.8 - 24 Apr 2023). I don't know how gogdl is finding a newer version than what GOG is making available.

(Please let me know if you require any screenshots, data, or logs.)

**Comment by imLinguin** [comment]
I think it's up to how we choose the build. Currently it's first from the list. But in this case first build is from different branch. I'll temporarily force the usage of `main` branch. This will be customizable when I finish the download refactor.

**Comment by imLinguin** [comment]
As workaround you may try to run gogdl update with `--build 56380777801514108`, and ignore update prompts in heroic

**Comment by imLinguin** [comment]
Could you try latest gogdl build?

**Comment by imLinguin** [comment]
This should be resolved in latest commits and in Heroic
