### ISSUE TITLE
Pillars of Eternity for Windows does not install correctly on Linux

### ISSUE THREAD

**Issue by JKingweb** [Heroic-Games-Launcher/heroic-gogdl#35]
During installation two directories are created, `PillarsOfEternity_Data` and `PillarsOfEternity_data`, which differ only in case. One file is contained in the former, and the rest of the files in the latter. Because Windows programs can only access one of the two directories and the former sorts first in binary order, the game can't find its files. 

Gogdl may need to do some case folding to avoid this situation.

**Comment by imLinguin** [comment]
I initially implemented some casefolding algorithm in the refactor. However that wasn't fast enough. I'll try to find solution to this issue. That could've been avoided if game devs would upload builds with consistent file naming across depots

**Comment by imLinguin** [comment]
I believe I solved this issue in download_refactor branch. Sadly you may not be able to test it yet as it drastically changes some data structures, rendering it useless with current Heroic release.

**Comment by imLinguin** [comment]
resolved in latest release
