### ISSUE TITLE
Streets of Rage 4 (Linux version) don't allow to install it

### ISSUE THREAD

**Issue by trinukso** [Heroic-Games-Launcher/heroic-gogdl#45]
When trying to install the game, it stays indefinitely calculating the size of the download and installation. I also have the DLC (Mr. X Nightmare). Thanks

![Captura desde 2024-04-04 22-04-30](https://github.com/Heroic-Games-Launcher/heroic-gogdl/assets/33544668/0b86688e-e39e-4a53-a703-6a09f2cbdb7a)

**Comment by imLinguin** [comment]
Our new method of downloading native games is still fairly experimental. Could you attach a log of gogdl after the failed attempt? It is available in Heroic settings 
![image](https://github.com/Heroic-Games-Launcher/heroic-gogdl/assets/62100117/6574102b-365f-4b8c-923f-c8f31c71c9d3)

**Comment by imLinguin** [comment]
Try using this build from GitHub action run https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/8316960653

**Comment by trinukso** [comment]
> Our new method of downloading native games is still fairly experimental. Could you attach a log of gogdl after the failed attempt? It is available in Heroic settings ![image](https://private-user-images.githubusercontent.com/62100117/320205222-6574102b-365f-4b8c-923f-c8f31c71c9d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MTA0NzAsIm5iZiI6MTcxMjQxMDE3MCwicGF0aCI6Ii82MjEwMDExNy8zMjAyMDUyMjItNjU3NDEwMmItMzY1Zi00YjhjLTkyM2YtYzhmMzFjNzFjOWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDEzMjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NzUwOTI0OTgwNmVhM2IxZWNjMzc1ZDRiODg4MWJkNTcwMTFmYTA0NTkyNmNkNWQxNDQ4ZWI5MjU1NTU0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VtpeG3_J-DpCx1v1L1pAjc8kLXzhIN45Mi5sArLnLCQ)

[gogdl.txt](https://github.com/Heroic-Games-Launcher/heroic-gogdl/files/14893695/gogdl.txt)

**Comment by trinukso** [comment]
> Try using this build from GitHub action run https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/8316960653

![Captura desde 2024-04-06 15-33-13](https://github.com/Heroic-Games-Launcher/heroic-gogdl/assets/33544668/311016a5-6c94-45c0-b27b-3705f641ce2b)

**Comment by imLinguin** [comment]
You need to make sure to mark it as executable

**Comment by trinukso** [comment]
> You need to make sure to mark it as executable

Sorry! Now works, thanks!

![Captura desde 2024-04-06 22-32-15](https://github.com/Heroic-Games-Launcher/heroic-gogdl/assets/33544668/7496706e-77b9-4ca9-83d9-bb85e38a9eeb)

**Comment by imLinguin** [comment]
Awesome, I'll make sure to update the binaries in the next Heroic release
